name: CMake on a single platform

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:

  BUILD_TYPE: Release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
       submodules: recursive 

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Run tests
      working-directory: ${{github.workspace}}/build/tests
      run: ./tests && ctest -C --output-on-failure
    
    - name: Create deb package
      working-directory: ${{github.workspace}}/build
      run: cpack -G DEB

    - name: Upload deb package
      uses: actions/upload-artifact@v4
      with:
        name: double_dispatch1-deb
        path: build/*.deb

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.${{ github.run_number }}
        release_name: Release v1.${{ github.run_number }}

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: double_dispatch1-1.${{ github.run_number }}
        path: build/*.deb